# Change these first
owner: bitsstdcheee # Your GitHub organization or username, where this repository lives
repo: luogu-status # The name of this repository

sites:
  - name: Google
    url: https://www.google.com
  - name: Wikipedia
    url: https://en.wikipedia.org
  - name: Luogu
    url: https://www.luogu.com.cn
  - name: Luogu CDN
    url: https://cdn.luogu.com.cn/fe/loader.js?ver=20230228-2
    expectedStatusCodes:
      - 200
      - 201
  - name: Luogu Discuss
    url: https://www.luogu.com.cn/discuss/lists
  - name: Luogu Contest
    url: https://www.luogu.com.cn/contest/list
  - name: Luogu Problem List
    url: https://www.luogu.com.cn/problem/list
  - name: Luogu Ti
    url: https://ti.luogu.com.cn/problemset
  - name: Luogu Class
    url: https://class.luogu.com.cn/course
  - name: Codeforces
    url: https://codeforces.com
  - name: HDU
    url: http://acm.hdu.edu.cn
  - name: VJudge
    url: https://vjudge.net
  - name: Github
    url: https://github.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /luogu-status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: There is **no** message
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 */2 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"
